# Generated by Django 3.1.2 on 2021-04-19 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210418_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='task_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
